[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "LightPeak"
name = "PeakChatOps"
description = "A chat system for PEAK. Basic messaging functionality with UI enhancements."
websiteUrl = "https://github.com/LIghtJUNction/PeakMods"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_PEAK = "5.4.2403"
Snosz-PhotonCustomPropsUtils = "1.1.0"
PEAKModding-PEAKLib_Core = "1.5.1"
PEAKModding-PEAKLib_UI = "1.5.0"
Cysharp-UniTask = "2.5.0"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "../../artifacts/thunderstore/"

[[build.copy]]
source = "../../artifacts/bin/PeakChatOps/release/com.github.LIghtJUNction.PeakChatOps.dll"
target = "plugins/"

[[build.copy]]
source = "../../artifacts/bin/PeakChatOps.API/release/PeakChatOps.API.dll"
target = "plugins/"

[[build.copy]]
source = "./CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../../LICENSE"
target = "/"

# The following config options only apply when using TCLI to publish to Thunderstore directly:

[publish]
# See communities at:
# https://thunderstore.io/api/experimental/community/
communities = [ "peak", ]

[publish.categories]
# See categories at:
# https://thunderstore.io/api/experimental/community/peak/category/
peak = [ "mods", ]
