// Decompiled with JetBrains decompiler
// Type: ACHIEVEMENTTYPE
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: F3E770A0-BBB5-4DDE-8A67-A45EBB5236BA
// Assembly location: G:\LIghtJUNction\steam\SteamLibrary\steamapps\common\PEAK\PEAK_Data\Managed\Assembly-CSharp.dll

#nullable disable
public enum ACHIEVEMENTTYPE
{
  NONE,
  TriedYourBestBadge,
  BeachcomberBadge,
  TrailblazerBadge,
  AlpinistBadge,
  VolcanologyBadge,
  CookingBadge,
  HappyCamperBadge,
  BoulderingBadge,
  ToxicologyBadge,
  ForagingBadge,
  EsotericaBadge,
  PeakBadge,
  LoneWolfBadge,
  ClutchBadge,
  BalloonBadge,
  LeaveNoTraceBadge,
  SpeedClimberBadge,
  BingBongBadge,
  NaturalistBadge,
  GourmandBadge,
  MycologyBadge,
  FirstAidBadge,
  SurvivalistBadge,
  AnimalSerenadingBadge,
  ArboristBadge,
  MentorshipBadge,
  KnotTyingBadge,
  EmergencyPreparednessBadge,
  AscenderBadge,
  PlundererBadge,
  BookwormBadge,
  EnduranceBadge,
  Ascent1,
  Ascent2,
  Ascent3,
  Ascent4,
  Ascent5,
  Ascent6,
  Ascent7,
  ResourcefulnessBadge,
  NomadBadge,
  UltimateBadge,
  CoolCucumberBadge,
  NeedlepointBadge,
  AeronauticsBadge,
  TwentyFourKaratBadge,
  DaredevilBadge,
  MegaentomologyBadge,
  AstronomyBadge,
  BundledUpBadge,
}
